language: perl

sudo: false

perl:
   - "5.26"
   - "5.24"
   - "5.22"
   - "5.18"
   - "5.16"
   - "5.14"

before_install:
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V
   - build-dist
   - cd $BUILD_DIR

install:
   - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
   - cpanm --quiet --notest Devel::Cover::Report::Coveralls
   - cpanm --quiet --notest --installdeps .

notifications:
  email: false
